files:
  - source: /content/articles/change-these-mobile-settings-for-better-privacy/index.md
    translation: /content/articles/change-these-mobile-settings-for-better-privacy/index.%two_letters_code%.md
