name: Mirroring

on:   
  push:
    branches: ["main"]

jobs:
  to_codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@codeberg.org:beginnerprivacy/beginnerprivacy.github.io.git"
          ssh_private_key: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}

  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:beginnerprivacy/beginnerprivacy.github.io.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}